---
title: "Alice Localizer Event Generator"
author: "Jojo Hu"
date: "9/21/2022"
output: html_document
---


# Compile the templates for Alice Localizer Event files
```{r}
order1 <- 
  list.files("/Volumes/data/projects/blast/data/derivatives/event_files/scripts/alice_localizer/Order1_EV_template", full.names = T, recursive = T)

order2 <- 
  list.files("/Volumes/data/projects/blast/data/derivatives/event_files/scripts/alice_localizer/Order2_EV_template", full.names = T, recursive = T)

read_txt <-
function(file) {
  file_name <- basename(file)
  file_name <- str_extract(file_name, "\\S+(?=.txt?)")
  
  file <- read.csv(file,  sep ="\t", stringsAsFactors = F, header = F)
  file[, "name"] <- file_name
  
  return(file)
}

order1 <- lapply(order1, read_txt)
order1 <- do.call(bind_rows, order1)

order2 <- lapply(order2, read_txt)
order2 <- do.call(bind_rows, order2)

library("dplyr")

colnames(order1) <- c("onset", "duration", "order", "trial_type")
colnames(order2) <- c("onset", "duration", "order", "trial_type")

order1 <- as.data.frame(order1)
order2 <- as.data.frame(order2)

order1 <-
  order1 %>%
  dplyr::arrange(onset) %>%
  dplyr::select(onset, duration, trial_type)

order2 <-
  order2 %>%
  dplyr::arrange(onset)  %>%
  dplyr::select(onset, duration, trial_type)
```


# Compile individuals' Alice event files
```{r}
adultEV <- 
  list.files("/Volumes/data/projects/blast/data/mri/in_scanner_behavioral/sl_raw_data/adult/alice_localizer",
             pattern = "run\\d+.csv$", full.names = T)
childEV <- 
  list.files("/Volumes/data/projects/blast/data/mri/in_scanner_behavioral/sl_raw_data/child/alice_localizer",
             pattern = "run\\d+.csv$", full.names = T)

adultEV <- lapply(adultEV, read.csv)
adultEV <- do.call(bind_rows, adultEV)

childEV <- lapply(childEV, read.csv)
childEV <- do.call(bind_rows, childEV)

# childEV[which(childEV$subjectID == "blast_c_0228"), "subjectID"] <- "blast_c_228"

ev <- bind_rows(adultEV, childEV)

# Extract order and run assigned for each participant
ev <- 
  ev %>%
  dplyr::select("subjectID", "randSeed", "list", "order", "run") %>%
  distinct(.) %>%
  filter(str_detect(subjectID, "blast")) %>%
  mutate(subjectID = as.character(subjectID))

ev$partID <- paste0("sub-", str_remove_all(ev$subjectID, "_"))

# Check whether participants assigned with the same order always have the same conditions
cond <-
  bind_rows(adultEV, childEV) %>%
  filter(str_detect(subjectID, "blast")) %>%
  dplyr::select("subjectID", "randSeed", "list", "order", "run", "trialNum", "condition", "onset") %>%
  distinct(.) %>%
  group_by("subjectID", "randSeed", "list", "order", "run") %>%
  arrange(onset)


cond_sum <-
  cond %>%
  dplyr::select("subjectID", "randSeed", "list", "order", "run", "condition", "trialNum") %>%
  group_by(subjectID, randSeed, list, order, run) %>%
  summarise(condition_sum = toString(condition)) %>%
  ungroup()

# Each order should have the same condition-order across runs and lists within subject. Order 1 and Order 2 is a between-subject variable.
cond %>%
  dplyr::select("subjectID", "randSeed", "list", "order", "run", "condition", "trialNum") %>%
  group_by(subjectID, randSeed, list, order, run) %>%
  dplyr::summarise(condition_sum = toString(condition)) %>%
  ungroup() %>%
  dplyr::select("order", "condition_sum") %>%
  distinct(.)

# Calculate duration of trials
allEV <- 
  dplyr::bind_rows(adultEV, childEV) %>%
  filter(str_detect(subjectID, "blast")) %>%
  dplyr::mutate(onset = as.numeric(as.character(onset))) %>%
  group_by(subjectID, randSeed, list, order, run) %>%
  arrange(subjectID, randSeed, list, order, run, onset, trialNum) %>%
  dplyr::mutate(duration = onset - lag(onset)) %>%
  filter(!is.na(onset))

allEV$duration <- append(allEV$duration[-1], NA)

# Last "Fix" block duration not available. 12 is the number by design.
allEV[which(is.na(allEV$duration) & allEV$trialNum == 16 & allEV$condition == "fix"), "duration"] <- as.numeric(12)

allEV %>%
  filter(is.na(duration))

allEV <-
  allEV %>%
  distinct(.) %>%
  dplyr::mutate(partID = paste0("sub-", str_remove_all(subjectID, "_"))) %>%
  dplyr::mutate(trial_type = condition) 

for (i in unique(allEV$partID)) {
  run1 <-
    allEV %>%
    filter(partID %in% i) %>%
    filter(run == 1) %>%
    dplyr::select(onset, duration, trial_type, trialNum)
  
  if(nrow(run1) > 0) {
    write.table(run1, paste0("/Volumes/data/projects/blast/data/derivatives/event_files/alice_localizer/", 
                           i, "_task-langloc_run-01_events.tsv"), 
              sep='\t', row.names = F)
  } else {
    print(i)
  }
}

for (i in unique(allEV$partID)) {
  run2 <-
    allEV %>%
    filter(partID %in% i) %>%
    filter(run == 2) %>%
    dplyr::select(onset, duration, trial_type, trialNum)
  
  if(nrow(run2) > 0) {
    write.table(run2, paste0("/Volumes/data/projects/blast/data/derivatives/event_files/alice_localizer/", 
                           i, "_task-langloc_run-02_events.tsv"), 
              sep='\t', row.names = F)
  } else {
    print(i)
  }
}
```


# Double check the event files all have positive onsets, same number of miniblocks
```{r}
cleanEV <-
  list.files("/Volumes/data/projects/blast/data/derivatives/event_files/alice_localizer",
             pattern = "*.tsv$", full.names = T)

cleanEV <- as.data.frame(cleanEV)

cleanEV$partID <- str_extract(cleanEV$cleanEV, "sub-blast(a|c)\\d+")
cleanEV$run <- str_extract(cleanEV$cleanEV, "(?<=run-0)\\d+")

read_langloc <- function(x) {
  temp <- read.csv(x, stringsAsFactors = F, sep="\t", header = T)
  
  if(nrow(temp) > 0) {
    temp$name <- x
  }

  return(temp)
}

longEV <- lapply(as.character(cleanEV$cleanEV), read_langloc)

langEV <- do.call(dplyr::bind_rows, longEV)

problem_file <- 
  langEV %>%
  group_by(name) %>%
  dplyr::summarise(n = n()) %>%
  filter(n != 16)

langEV %>%
  filter(onset < 0 | duration < 0)

remove_file <- function(x) {
  if (file.exists(x)) {
    print(basename(x))
    file.remove(x)
  }
}

lapply(problem_file$name, remove_file)
```


```{r}
# Double check that there is lang loc event files that have more than 16 blocks
langEV %>%
  group_by(name) %>%
  dplyr::summarise(n = n()) %>%
  filter(n != 16)

# Double check that there is no lang loc event files with negative onsets
langEV %>%
  filter(onset < 0)
```


# Remove existing event files in bids folders (only use if needed)
```{r}
alice_from <- 
  list.files("/Volumes/data/projects/blast/data/bids", 
              pattern = "sub-blast(a|c)*", full.names = T, recursive = F)

alice_from <- 
  list.files(paste0(alice_from, ""), 
              pattern = "sub-blast(a|c)\\d+_task-langloc_run-\\d+_events.tsv$", full.names = T, recursive = F)

file.remove(alice_from)

bk <- alice_from
```
# Create event files for each individual and move into their bids/func folder
```{r}
cleanEV <- 
  list.files("/Volumes/data/projects/blast/data/derivatives/event_files/alice_localizer",
             pattern = "*.tsv$", full.names = T)

cleanEV <- as.data.frame(cleanEV)

cleanEV$partID <- str_extract(cleanEV$cleanEV, "sub-blast(a|c)\\d+")
cleanEV$run <- str_extract(cleanEV$cleanEV, "(?<=run-0)\\d+")

alice_from <- 
  list.files("/Volumes/data/projects/blast/data/bids", 
              pattern = "sub-blast(a|c)*", full.names = T, recursive = F)

alice_from <- as.data.frame(alice_from)

alice_from[,"partID"] <- str_extract(alice_from$alice_from, "sub-blast(a|c)\\d+")

alice_move <- merge(alice_from, cleanEV, by = c("partID"), all.x = T)

alice_move$alice_to <- file.path(alice_move$alice_from, "func", basename(as.character(alice_move$cleanEV)))

alice_move <-
  alice_move %>%
  distinct(.)

file.copy(file.path(alice_move$cleanEV), file.path(alice_move$alice_to), 
          overwrite = T,
          copy.mode = TRUE, 
          copy.date = TRUE)

file.copy("/Volumes/data/projects/blast/data/bids/task-langloc_bold.json", "/Volumes/data/projects/blast/data/derivatives/fmriprep/", 
          overwrite = F,
          copy.mode = TRUE, 
          copy.date = TRUE)
```